Repository nb04-howdoilook-7/nb04-howdoilook-team7, pull requests merged in 2025-08, with the labels that each got.

#5 feat: 스타일 API 초안 작성 및 스키마 오타 수정
  backend/Routers/Style.js
  backend/Services/StyleService.js
  backend/prisma/schema.prisma
Labels: todo, 개발

#42 태그 목록 조회, 이미지 업로드 모듈화 코드
  backend/.gitignore
  backend/Routers/Style.js
  backend/Services/StyleService.js
  backend/Utils/CalculateRanking.js
  backend/Utils/imageUpload.js
  backend/Validators/StyleValidator.js
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/uploads/0beb4be4e033a6a7ad79e2add68f28d3.png
  backend/uploads/9ac65c782cf576cb6cfce75095173a4d.png
  backend/uploads/bd4af68631b3130f1330f1fc4136a599.png
  frontend/.env.sample
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/layout.tsx
  frontend/src/libs/shared/util-util/checkIsNotEmpty.ts
  frontend/src/services/api.ts
  frontend/src/services/fetch.ts
Labels: 개발, 해결, frontend 수정

#46 feat: Cloudinary를 이용한 클라우드 이미지 저장 기능 통합
  backend/Services/StyleService.js
  backend/package-lock.json
  backend/package.json
  frontend/next.config.js
Labels: 추가 구현, frontend 수정

#47 fix: 태그 검색 및 중첩 검색 안되는 오류 수정
  backend/Services/StyleService.js
Labels: 수정, 해결

#55 refactor: 스타일 api 컨트롤러 추가 리팩터링
  backend/Controllers/CommentController.js
  backend/Controllers/CurationController.js
  backend/Controllers/StyleController.js
  backend/Middlewares/asyncHandler.js
  backend/Middlewares/errorHandler.js
  backend/Routers/Comment.js
  backend/Routers/Curation.js
  backend/Routers/Ranking.js
  backend/Routers/Style.js
  backend/Services/CommentService.js
  backend/Services/CurationService.js
  backend/Services/StyleService.js
  backend/Utils/CloudinaryUtils.js
  backend/app.js
  frontend/src/libs/curating/feature-curating/CuratingsContent.tsx
Labels: 수정
